apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{ .Values.service.dbport }}
      targetPort: {{ .Values.service.dbtargetPort }}
  type: ClusterIP

