apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  MYSQL_DATABASE: d29yZHByZXNz    
  MYSQL_USER: a2FjcGVy             
  MYSQL_PASSWORD: MTIz  
  MYSQL_ROOT_PASSWORD: MTIz
