apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  MYSQL_DATABASE: wordpress    
  MYSQL_USER: kacper             
  MYSQL_PASSWORD: "123"  
  MYSQL_ROOT_PASSWORD: "123"
