apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storage }}
provisioner: {{ .Values.storage.provisioner }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
