apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: {{ .Values.wordpress.containerPort }}
          env:
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
            - name: WORDPRESS_DATABASE_USER
              value: kacper
            - name: WORDPRESS_DATABASE_PASSWORD
              value: "123"
            - name: WORDPRESS_DATABASE_HOST
              value: database
          volumeMounts:
            - name: wordpress-storage
              mountPath: /bitnami/wordpress
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: {{ .Values.wordpress.pvcname }}
        - name: tmp
          emptyDir: {}
