apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpress.pvcname }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.storage }}
  storageClassName: {{ .Values.storage.storagename }}
