apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: {{ .Values.service.wpport }}
      targetPort: {{ .Values.service.wptargetport }}
  type: ClusterIP
