apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: {{ .Values.service.wp-port }}
      targetPort: {{ .Values.service.wp-targetport }}
  type: ClusterIP
