apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: incubator-cluster
spec:
  teamId: "incubator"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    postgres:  # database owner
      - superuser
      - createdb
    foo_user: []  # role for application foo
  databases:
    postgres: zalando  # dbname: owner
  preparedDatabases:
    postgres: {}
  postgresql:
    version: "14"
