apiVersion: apps.baloise.dev/v1alpha1
kind: VirtualMachineCluster
metadata:
  name: example
spec:
  flavor: small
  instances: 2
  os: linux
  diskSize: 20Gi
  ports:
    - name: http
      port: 80
      targetPort: 8080 # optional - defaults to port
      protocol: TCP # optional - defaults to TCP
      ingress:
        host: example-vm.apps.baloise.dev