gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 566986bc53592942bb09d33763bbc471ccbe817d
  network:
    http:
      ingress:
        host: gitops-demo.baloise.dev
        annotations:
          external-dns.alpha.kubernetes.io/hostname: gitops-demo.baloise.dev
