kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jupyterhub
spec:
  host: jupyterhub-jupyterhub.apps.okd.baloise.dev
  to:
    kind: Service
    name: hub
    weight: 100
  port:
    targetPort: hub
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None