kind: ConfigMap
metadata:
  name: nginx-config
apiVersion: v1
data:
  default.conf: |
    server {
      listen 8080;
        location / {
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_set_header Host-Real-IP  $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-Pcol https;
          proxy_intercept_errors on;
          proxy_set_header Host sec.gov;
          proxy_pass https://sec.gov;
        }
    }
