gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 0d771e224675fb64a3fe5b2ce270a9679f71f4933bf36e7f8aba043829f49441
  replicaCount: 2
  network:
    http:
      ingress:
        host: gitops-nginx-demo-c7003101.apps.baloise.dev
