gitops-demo:
  image:
    repository: registry.baloise.dev/example/gitops-nginx-demo
    tag: 5b7906486a400756fba354032a0f67cc79cad46c
  network:
    http:
      ingress:
        host: gitops-nginx-demo-niiku-patch-1-bb5-preview.apps.baloise.dev
