apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ .Release.Name }}
spec:
  endpoints:
    - dnsName: {{ .Values.baloise-design-system-docs.network.http.ingress.host }}
      recordType: A
      targets: [""]
