apiVersion: v2
version: 1.0.0
name: bitbucketserver-test
dependencies:
  - name: bitbucket
    version: 1.4.0
    repository: https://atlassian.github.io/data-center-helm-charts
    alias: bitbucket-chart
  - name: postgresql-ha
    version: 9.3.5
    repository: https://charts.bitnami.com/bitnami
    alias: postgres-chart