bitbucket-chart:
 image:
  repository: quay.balgroupit.com/devops/bitbucket
  tag: "8.3"
 replicaCount: 2
 database:
  url: postgresql-ha-pgpool.bitbucket-test.svc.cluster.local
  credentials:
    secretName: bitbucketdbconnect 
    usernameSecretKey: username
    passwordSecretKey: password
 volumes:
  localHome:
    persistentVolumeClaim:
      create: true
  sharedHome:
    persistentVolume:
      create: false
    persistentVolumeClaim:
      create: true
      storageClassName: cephfs
    nfsPermissionFixer: 
      enabled: false   
 bitbucket:
  securityContextEnabled: false
  license:
    secretName:
    secretKey: license-key
  sysadminCredentials:
    secretName:
    usernameSecretKey: username
    passwordSecretKey: password
    displayNameSecretKey: displayName
    emailAddressSecretKey: emailAddress
  displayName:
  clustering:
    enabled: false
  elasticSearch:
    credentials:
      secretName:
      usernameSecretKey: username
      passwordSecretKey: password
  additionalEnvironmentVariables: 
   - name: NO_SEARCH
     value: "1"
postgres-chart:    
  global:
   postgresql:
     username: "postgres"
     password: "password"
     database: "standard"
     repmgrUsername: "repmgr"
     repmgrPassword: "password"
     repmgrDatabase: "repmgr"
  postgresql:
   image: 
    repository: quay.balgroupit.com/devops/bitbucket
    tag: postgresql-repmgr-14.5.0-debian-11-r3
   podSecurityContext:
     enabled: false
   containerSecurityContext:
     enabled: false
   username: postgres
   password: "password"
   database: "standard"
   repmgrPassword: "password"
  pgpool:
    image:
    repository: quay.balgroupit.com/devops/bitbucket
    tag: pgpool-4.3.2-debian-11-r28
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  metrics:
    podSecurityContext:
      enabled: false
    