apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webserver
spec:
  replicas: {{.values.deployement.replicas}}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache-container
          image: {{.values.deployement.image}}
          ports:
            - containerPort: {{.values.deployement.containerPort}}
          volumeMounts:
            - name: app-config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
            - name: pid
              mountPath: /usr/local/apache2/logs
      volumes:
        - name: app-config
          configMap:
            name: app-config
        - name: pid
          emptyDir: {}
