apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webserver.route
spec:
  to:
    kind: Service
    name: webserver-service
  port:
    targetPort: {{.values.route.targetPort}}
  tls:
    termination: edge
