apiVersion: v1
kind: Service
metadata:  
  name: webserver-service
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
