apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: database        
          image: ghcr.io/kacper08480/mysql-3:latest
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: kacper
            - name: MYSQL_PASSWORD
              value: "123"
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database-data
              mountPath: /var/lib/mysql
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-pvc
