wordpress:
  replicas: 1
  image:
  port: 8080
service:
  targetPort: 8080
  port: 8080
database:
  replicas: 1
  image: ghcr.io/kacper08480/mysql-4:latest
  containerPort: 3306
  pvcname: 'database-pvc'
storage:
  storagename: 'wp-storage'
  storage: 5gi
  provisioner: kubernetes.io/portworx-volume
