wordpress:
  replicas: 1
  image: bitnami/wordpress:6.8.1-debian-12-r5
  containerPort: 8080
  pvcname: 'wordpress-pvc'
service:
  wptargetPort: 8080
  wpport: 8080
  dbtargetPort: 3306
  dbport: 3306
database:
  replicas: 1
  image: registry.redhat.io/rhel8/mariadb-105
  containerPort: 3306
  pvcname: 'database-pvc'
storage:
  storagename: 'wp-storage'
  storage: 5Gi
  provisioner: kubernetes.io/portworx-volume
route:
  targetPort: 8080
