wordpress:
  replicas: 1
  image:
  port: 8080
service:
  targetPort: 8080
  port: 8080
database:
  replicas: 1
  image:
  port: 8080
storage:
  storagename: 'wp-storage'
  storage: 5gi
  provisioner: kubernetes.io/portworx-volume
