apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: wordpress
          image: bitnami/wordpress:6.5.4-debian-11-rXX
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DATABASE_HOST
              value: db-service
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
            - name: WORDPRESS_DATABASE_USER
              value: kacper
            - name: WORDPRESS_DATABASE_PASSWORD
              value: "123"
          volumeMounts:
            - name: wordpress-storage
              mountPath: /bitnami/wordpress/wp-content
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: tmp
          emptyDir: {}
