apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: wordpress
          image: bitnami/wordpress:6.8.1-debian-12-r5
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: kacper
            - name: MYSQL_PASSWORD
              value: "123"
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          volumeMounts:
            - name: wordpress-storage
              mountPath: /bitnami/wordpress
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: tmp
          emptyDir: {}
