apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: registry.redhat.io/rhel7/wordpress-36
          ports:
            - containerPort: 8080
          env:
            - name: WORDPRESS_DB_HOST
              value: db-service:3306
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: kacper
            - name: WORDPRESS_DB_PASSWORD
              value: "123"
          volumeMounts:
            - name: app-config
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
            - name: pid
              mountPath: /usr/local/apache2/logs
            - name: wordpress-storage
              mountPath: /var/www/html/wp-content
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: app-config
          configMap:
            name: app-config
        - name: pid
          emptyDir: {}
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
