kind: Tenant
apiVersion: minio.min.io/v2
metadata:
  name: grafana-tempo-minio-test
  labels:
    app: minio
spec:
  certConfig: {}
  configuration:
    name: storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: 'quay.io/minio/minio@sha256:f95dc4fc35439654a71300f765b485e114e7a720318dbce24ccd4f324d1475cf' # image provided from operator
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - containerSecurityContext: {}
      name: pool-0
      securityContext: {}
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      volumesPerServer: 2
  priorityClassName: ''
  requestAutoCert: true
  serviceAccountName: ''
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ''
  users:
    - name: storage-user
