apiVersion: v1
kind: Secret
metadata:
  name: grafana-tempo-minio-test
stringData:
  endpoint: http://minio.grafana-tempo-minio-test.svc:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: supersecret
type: Opaque