apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  storage:
    secret:
      name: grafana-tempo-minio-test
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: '2'

  extraConfig:
    tempo:
      server:
        grpc_server_max_recv_msg_size: 52430000 # 50 MiB
        grpc_server_max_send_msg_size: 52430000 # 50 MiB
      compactor:
        compaction:
          # -- Duration to keep blocks
          block_retention: 672h # 4 weeks

  template:

    queryFrontend:
      jaegerQuery:
        enabled: true

    compactor:
      resources:
        limits:
          cpu: '3'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi

    ingester:
      replicas: 3

    querier:
      frontend_worker:
        grpc_client_config:
          # Sets the maximum gRPC message size that the querier accepts.
          max_send_msg_size: 52430000 # 50 MiB
      trace_by_id:
        query_timeout: 10s