apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  storage:
    secret:
      name: grafana-tempo-minio-test
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: '2'
  extraConfig:
    tempo:
      compactor:
        compaction:
          # -- Duration to keep blocks
          block_retention: 672h # 4 weeks

  template:

    queryFrontend:
      jaegerQuery:
        enabled: true

    compactor:
      resources:
        limits:
          cpu: '3'
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi

